### ISSUE TITLE
fsutils is giving access errors on Win 7 32 and 64 bits all the way to windows 10

### ISSUE THREAD

**Issue by pinedoj** [MrYsLab/python_banyan#2]
fsutils is giving access errors on Win 7 32 and 64 bits all the way to windows 10
One fix is on banyan_base.py
               try:
                    name=p.name()  #<-- This will read the name 
                except Exception as e:
                    continue
                #p_command = p.cmdline()  #<-- This was original line
                try:
                    #if any('backplane' in s for s in p_command):  #<-- This was original line when received a list
                    if 'backplane.exe'== name:  #<-- Since we stored the name on one variable no need to check a list

**Comment by MrYsLab** [comment]
This bug is fixed with version 2.4. Thanks for letting me know about it.
