### ISSUE TITLE
[DOC typo] maybe, not sure

### ISSUE THREAD

**Issue by willmendil** [MrYsLab/python_banyan#6]
I'm going through the docs for banyan , and you are right it does sound perfect for the job. However, they may be a type here [https://mryslab.github.io/python_banyan/#common_messaging_protocol/](https://mryslab.github.io/python_banyan/#common_messaging_protocol/)

at the bottom you say 

> 
> GPIO Operation | OneGPIO Message
> -- | --
> Set Digital Output Pin State | {"command": "digital_write", "pin": PIN, "tag": "TAG", "value": VALUE}
> 
 and below you show an example: 

> **{'command': 'digital_write', 'tag': 'green_led', 'value': 1 }**

Are you sure the `"pin"; PIN`, should be in the table?

**Comment by willmendil** [comment]
second typo :

[https://mryslab.github.io/python_banyan/#banyan_gateways/](https://mryslab.github.io/python_banyan/#banyan_gateways/)

second phrase:

>  It it subscribes

**Comment by willmendil** [comment]
[https://mryslab.github.io/python_banyan/#banyan_gateways/](https://mryslab.github.io/python_banyan/#banyan_gateways/)
"the tag" looks out of place


Line 87 creates an empty tags_dictionary. When a pin mode is set and a tag is provided, **the tag**, an entry is made into this dictionary with the tag as its key and the pin number as the entry's value.

**Comment by willmendil** [comment]
[https://mryslab.github.io/python_banyan/#banyan_gateways/](https://mryslab.github.io/python_banyan/#banyan_gateways/)

Some Specific Command Examples
To illustrate the flexibility of using the OneGPIO specification, let's look **an** at some sample OneGPIO command implementations. Both examples presented below are from the Raspberry Pi Gateway.

**Comment by willmendil** [comment]
[https://mryslab.github.io/python_banyan/#example8/](https://mryslab.github.io/python_banyan/#example8/)

> NOTE: For Linux, Mac and Raspberry PI users, the Launcher requires xterm to installed on your system.

shouldn't it be "to be installed" ? Maybe you could explain why.

**Comment by willmendil** [comment]
[https://github.com/MrYsLab/python_banyan/blob/master/projects/OneGPIO/message_specification/OneGPIO.pdf](https://github.com/MrYsLab/python_banyan/blob/master/projects/OneGPIO/message_specification/OneGPIO.pdf)

You have writte `'tag': "TAG"` twice for the **Set Pin Mode To SONAR** in the pdf

**Comment by MrYsLab** [comment]
Thanks for all the great comments. I have added some clarifying text for the first comment. Essentially if a tag is set, you may then use either the tag or pin number.

Something weird with the browsers. If I use firefox on Linux the tables are not rendered properly, but if I use Chrome, all looks correct.
