### ISSUE TITLE
Adding Makefile, getting to know project

### ISSUE THREAD

**Issue by zacharyjones123** [MrYsLab/python_banyan#7]
Hello! I've been looking into this project to make my own escape room with a Raspberry Pi! This was so awesome to stumble across.

I'm curious how you developed this library and anything I could add to it!

In my job we put Makefiles in our projects so we can run commands like `make-test`, `make-build` and etc to help with developing locally so that is one example.

**Comment by MrYsLab** [comment]
Basically, I use PyCharm. I provided a much more detailed answer in a private email to @zacharyjones123.
